build: off
version: "{build}"

image:
  - Visual Studio 2019
  - macOS

platform:
  - x64

environment:
  matrix:
    - PYTHON_WIN: "C:\\Python38-x64"
      PYTHON_MAC: "venv3.9"
      PYTHON_UBU: "venv3.9/bin/python"
      PYTHON_VERSION: "3.9"
      PYTHON_ARCH: "64"


for:
  - 
    matrix:
      only:
        - image: Visual Studio 2019
    init:
      - "ECHO %PYTHON_WIN% %PYTHON_VERSION% %PYTHON_ARCH%"
      - "%PYTHON_WIN%\\python.exe --version"

    install:
      - "%PYTHON_WIN%\\python.exe -m pip install -r requirements.txt"
      - "%PYTHON_WIN%\\python.exe -m pip install https://freelanguagetools.org/python_lzo-1.12-cp38-cp38-win_amd64.whl"
      - "%PYTHON_WIN%\\python.exe -m pip install cx_freeze"
      - "%PYTHON_WIN%\\python.exe -m pip install ."
      - "cd cx_freeze"
      - "%PYTHON_WIN%\\python.exe setup.py bdist_msi"
      - ps: "ls"

    artifacts:
      path: cx_freeze/dist/*.msi
      name: Windows App
        
  -
    matrix:
      only:
        - image: macOS
    
    init:
      - "ls"
      - "echo $PYTHON_MAC $PYTHON_VERSION $PYTHON_ARCH"
      - "$HOME/$PYTHON_MAC/bin/python --version"
    
    install:
      - "$HOME/$PYTHON_MAC/bin/python -m pip install -r requirements.txt"
      - "$HOME/$PYTHON_MAC/bin/python -m pip install -r python-lzo"
      - "$HOME/$PYTHON_MAC/bin/python -m pip install cx_freeze"
      - "$HOME/$PYTHON_MAC/bin/python -m pip install ."
      - "cd cx_freeze"
      - "$HOME/$PYTHON_MAC/bin/python setup.py bdist_mac --iconfile icon.icns --bundle-name=vocabsieve --custom-info-plist Info.plist -q"
      - "npm i -g create-dmg"
      - "cd build"
      - "create-dmg vocabsieve.app || true"
      - "mv \"vocabsieve undefined.dmg\" vocabsieve-$APPVEYOR_REPO_TAG_NAME-macos.dmg"
      - "ls"
      - "cd ../../"

    artifacts:
      path: cx_freeze/build/*.dmg
      name: Mac App


deploy:
  description: new release
  provider: GitHub
  auth_token:
    secure: GMdaty/QRo0ATH06dsAQ2LtyUTQUuk45Pp23OTDKBevsBdnhCPW6iAGPcYO1Vyj3
  artifact: Windows App, Mac App
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
