build: off
version: "{build}"

image:
  - Ubuntu2004
  - macos-bigsur
  - Visual Studio 2022

platform:
  - x64

environment:
  matrix:
    - PYTHON_WIN: "C:\\Python38-x64"
      PYTHON_MAC: "venv3.10"
      PYTHON_UBU: "venv3.8"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"


for:
  - 
    matrix:
      only:
        - image: Visual Studio 2022
    init:
      - "ECHO %PYTHON_WIN% %PYTHON_VERSION% %PYTHON_ARCH%"
      - "%PYTHON_WIN%\\python.exe --version"

    install:
      - "%PYTHON_WIN%\\python.exe -m pip install wheel"
      - "%PYTHON_WIN%\\python.exe -m pip install https://freelanguagetools.org/python_lzo-1.12-cp38-cp38-win_amd64.whl"
      - "%PYTHON_WIN%\\python.exe -m pip install -r requirements.txt"
      - "%PYTHON_WIN%\\python.exe -m pip install cx_freeze==6.13"
      - "cd cx_freeze"
      - "cd win"
      - "%PYTHON_WIN%\\python.exe setup.py bdist_msi"
      - "cd ..\\win_debug"
      - "%PYTHON_WIN%\\python.exe setup.py bdist_msi"
      - ps: "ls"

    artifacts:
      - path: cx_freeze/win/dist/*.msi
        name: Windows App
      - path: cx_freeze/win_debug/dist/*.msi
        name: Windows App (debug)
        
  -
    matrix:
      only:
        - image: macos-bigsur
    
    init:
      - "ls"
      - "echo $PYTHON_MAC $PYTHON_VERSION $PYTHON_ARCH"
      - "$HOME/$PYTHON_MAC/bin/python --version"
    
    install:
      - "$HOME/$PYTHON_MAC/bin/python -m pip install wheel"
      - "brew install lzo"
      - "$HOME/$PYTHON_MAC/bin/python -m pip install python-lzo"
      - "$HOME/$PYTHON_MAC/bin/python -m pip install -r requirements.txt"
      - "$HOME/$PYTHON_MAC/bin/python -m pip install cx_freeze"
      - "cd cx_freeze/mac"
      - "$HOME/$PYTHON_MAC/bin/python setup.py bdist_mac --iconfile ../icon.icns --bundle-name=vocabsieve --custom-info-plist ../Info.plist -q"
      - "npm i -g create-dmg"
      - "cd build"
      - "create-dmg vocabsieve.app || true"
      - "mv \"vocabsieve undefined.dmg\" vocabsieve-$APPVEYOR_REPO_TAG_NAME-macos.dmg"
      - "cd ../.."

    artifacts:
      - path: cx_freeze/mac/build/*.dmg
        name: Mac App

  -
    matrix:
      only:
        - image: Ubuntu2004
    init:
      - "echo $PYTHON_UBU $PYTHON_VERSION $PYTHON_ARCH"
      - "$HOME/$PYTHON_UBU/bin/python --version"
    install:
      - "sudo apt install -y liblzo2-dev zlib1g-dev"
      - "$HOME/$PYTHON_UBU/bin/python -m pip install python-appimage"
      - "cp vocabsieve.{desktop,png} recipe/"
      - "echo $(pwd)"
      - "echo $(pwd) | cat - recipe/requirements.txt > tmpfile && mv tmpfile recipe/requirements.txt"
      - "$HOME/$PYTHON_UBU/bin/python -m python_appimage build app -p 3.10 recipe"
      - "ls"
      - "echo $(grep version setup.cfg | awk '{print $3}')"
      - "mv VocabSieve-x86_64.AppImage VocabSieve-v$(grep version setup.cfg | awk '{print $3}')-linux-amd64.AppImage"

    artifacts:
      - path: "*.AppImage"
        name: Linux App


deploy:
  - provider: GitHub
    description: new release
    auth_token:
      secure: GMdaty/QRo0ATH06dsAQ2LtyUTQUuk45Pp23OTDKBevsBdnhCPW6iAGPcYO1Vyj3
    artifact: Windows App, Mac App, Linux App
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
