title: VocabSieve Manual
description: Documentation of VocabSieve features and usage
theme: just-the-docs

url: https://docs.freelanguagetools.org/

aux_links:
  VocabSieve homepage: https://github.com/FreeLanguageTools/vocabsieve
