# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Binaries

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Build application
      run: |
        python -m pip install --upgrade pip
        pip install https://freelanguagetools.org/python_lzo-1.12-cp38-cp38-win_amd64.whl
        pip install -r requirements.txt
        pip install wheel
        pip install cx_freeze
        ls
        cd cx_freeze/win_debug
        python setup.py bdist_msi
        cd ../..
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        - name: Windows app (debug)
          path: "cx_freeze/win_debug/dist/*.msi"